### PR TITLE
First pass of review

### PR DESCRIPTION
**Pull request by yvanlebras**

### CODE REVIEW

**Comment by yvanlebras** [comment]
One can add others authors than Yves I think like Dominique and maybe others like Claire Bissery. Maybe you can ask Dominique to be sure (and also for the link / reference to put) ?

**Comment by yvanlebras** [comment]
Arf, sorry, I was thinking the underscore in unitobs name was the reason of the error with frenchbbs file and communitymetrics calculation tool... but in fact I made a mistake on my tests... Sorry.

The error is:
```
Error in names(x) <- value : 
  'names' attribute [2] must be the same length as the vector [1]
Calls: calcBiodiv.f -> colnames<-
Execution halted
```
Any idea ?

**Comment by yvanlebras** [comment]
For glm tool, an error, not very informative I think is displayed when you don't select a well formatted input file and/or a bad variable (for example response variable, is not column3 of metrics file):
```
Error in glmmTMB(exprML, family = loiChoisie, data = tmpData) : 
  object 'loiChoisie' not found
Calls: modeleLineaireWP2.unitobs.f -> glmmTMB
Execution halted
```
Where the user can think the tool has difficulties to find family but in fact this is not really the problem. It can be of interest to try ameliorate this behavior.

**Comment by ColineRoyaux** [comment]
I never had this error with 'LoiChoisie' I haven't formated the file check yet maybe it will get the "wrong file" error better and for the part "wrong variable" maybe I can add stop("Selected metric class doesn't fit, you should select an integer or a numeric variable") as the last alternative in the switch line 126 ?

**Comment by ColineRoyaux** [comment]
About the "error in names" I get this error when the input is emptied at one point in the script but I corrected it for the french bbs file already normally so I don't get why you have it now ... Maybe it's not the latest version I'm going to check

**Comment by ColineRoyaux** [comment]
I definitely have a problem with script versions on gitHub... dependencies are called in the latest version on my computer and errors with colnames are corrected sorry about that !

**Comment by yvanlebras** [comment]
Don't worry, be happy!

**Pull request merged**
